[tool.poetry]
name = "fcm"
version = "0.1.0"
description = ""
authors = ["Aman Phatak <aman@zeffo.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
firebase-admin = "^6.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
